### PR TITLE
space encoding fix for overrides in cli

### LINKED ISSUE #8372: CLI bug when using an override with a node name with several spaces.
### What happened?

using the command: 
```
[Soil]=Chickpea.apsimx;[Black Vertosol-Mywybilla (Bongeen No001)] 
```
causes an issue where it was unable to locate the file. Needs more investigation as to why.

### Update
In the section that handles overrides, encoded commands need to handled correctly. (Line 94)

### What Operating System are you on?

Windows

### PR DESCRIPTION
**Pull request by ric394**
resolves #8372

### CODE REVIEW

**Comment by ric394** [comment]
retest this please jenkins

File: Models/Core/ConfigFile/ConfigFile.cs [hunk 1]
```diff
@@ -326,22 +327,25 @@ public static List<string> EncodeSpacesInCommandList(List<string> commandsList)
...
+                            //int indexOfSpace = trimmedSection.IndexOf(' ');
+                            //if (indexOfSpace != -1)
+                            //{
+                            //    string tempSection = trimmedSection.Insert(indexOfSpace, "@");
+                            //    int newIndexOfSpace = tempSection.IndexOf(" ");
+                            //    fixedSection = tempSection.Remove(indexOfSpace, 1);
+                            //    correctedLine += fixedSection;
+                            //}
+                            //else correctedLine += trimmedSection;
+                            fixedSection = trimmedSection.Replace(' ', '@');
```
Comment (hol353) [inline Models/Core/ConfigFile/ConfigFile.cs:347]: Remove commented code please - line 94 and lines 338-346

Comment (ric394) [reply Models/Core/ConfigFile/ConfigFile.cs:338]: This is now done.
