### PR TITLE
Tidy up logic and fix a few bugs.  Add some error checks

### LINKED ISSUE #9967: A few bugs identified in AccumulateFunctionGeneral
### What happened?

Some logic not working as expected.  Error messages needed to avoid dysfunctional configuration

### What Operating System are you on?

Windows

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
resolves #9967

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
@par @ric394 @hol353 Please review and merge if OK

File: Models/Functions/AccumulateFunctionGeneral.cs [hunk 1]
```diff
@@ -159,17 +177,51 @@ private void OnConnectToEvents(object sender, EventArgs args)
...
         private void OnAccumulateEvent(object sender, EventArgs e)
         {
+            if (!String.IsNullOrEmpty(EndDate))
+            {
+                DateTime endDate = new DateTime();
+                DateTime.TryParse(EndDate + "-" + clock.Today.Year.ToString(), out endDate);
+
+                if (DateTime.Compare(clock.Today, endDate) >= 0) //If today is after end date
+                {
+                    AccumulateToday = false;
```
Comment (hol353) [inline Models/Functions/AccumulateFunctionGeneral.cs:187]: Can we change this to ```AccumulateToday = DateTime.Compare(clock.Today, endDate) < 0;```

Comment (HamishBrownPFR) [reply Models/Functions/AccumulateFunctionGeneral.cs:195]: Thanks @hol353 I have tidied that up.  It is possible to do it in the way you ask for the start conditions (StartDate and StartStage)  The end conditions need to just be a test to switch to false otherwise it is possile the start condition is false but the end condition is true and accumulation will happen when not intended
