### PR TITLE
9137 Soil Download Issue

### LINKED ISSUE #9137: Exception thrown after soil is downloaded from APSoil or ISRIC
### What happened?

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=ApsimNG
  StackTrace:
   at UserInterface.Presenters.ProfilePresenter.PopulateChemicalGraph(GraphView graph, Double[] thickness, Double[] pH, PHUnitsEnum phUnits, IEnumerable`1 solutes) in ApsimNG\Presenters\ProfilePresenter.cs:line 282
```

image

### What Operating System are you on?

Windows

### PR DESCRIPTION
**Pull request by par456**
Resolves #9137 

Changed to https for apsoil requests, also did some checking for other bugs encountered when testing.

### CODE REVIEW

File: ApsimNG/Presenters/SoilDownloadPresenter.cs [hunk 1]
```diff
@@ -348,10 +348,33 @@ private async Task<IEnumerable<SoilFromDataSource>> GetApsoilSoilsAsync(IProgres
...
-                double longitude = Convert.ToDouble(longitudeEditBox.Text, System.Globalization.CultureInfo.InvariantCulture);
-                double radius = Convert.ToDouble(radiusEditBox.Text, System.Globalization.CultureInfo.InvariantCulture);
+                double latitude = 0;
+                double longitude = 0;
+                double radius = 0;
+                try 
+                {
+                    latitude = Convert.ToDouble(latitudeEditBox.Text, System.Globalization.CultureInfo.InvariantCulture);
+                }
+                catch (Exception e)
```
Comment (hol353) [inline ApsimNG/Presenters/SoilDownloadPresenter.cs:358]: Rather then using try / catch to determine if a string can be converted to double, use ```double.TryParse``` method

**Review by hol353 — CHANGES_REQUESTED** [review]

File: ApsimNG/Presenters/SoilDownloadPresenter.cs (hunk 1 above)
Comment (par456) [reply ApsimNG/Presenters/SoilDownloadPresenter.cs]: Yep, that's a better idea, updated.

File: ApsimNG/Presenters/SoilDownloadPresenter.cs [hunk 2]
```diff
@@ -348,10 +348,26 @@ private async Task<IEnumerable<SoilFromDataSource>> GetApsoilSoilsAsync(IProgres
...
             {
-                // fixme: Shouldn't this be using the current culture?
-                double latitude = Convert.ToDouble(latitudeEditBox.Text, System.Globalization.CultureInfo.InvariantCulture);
-                double longitude = Convert.ToDouble(longitudeEditBox.Text, System.Globalization.CultureInfo.InvariantCulture);
-                double radius = Convert.ToDouble(radiusEditBox.Text, System.Globalization.CultureInfo.InvariantCulture);
+                bool canParse;
+                
+                double latitude;
+                canParse = double.TryParse(latitudeEditBox.Text, out latitude);
+                if(!canParse) {
```
Comment (hol353) [inline ApsimNG/Presenters/SoilDownloadPresenter.cs:355]: This can be combined onto one line like this:
```c#
if (!double.TryParse(latitudeEditBox.Text, out double latitude)
```

Simpler?

Comment (par456) [reply ApsimNG/Presenters/SoilDownloadPresenter.cs:355]: yes, yes it can.

**Review by hol353 — APPROVED** [review]
