### PR TITLE
Manager read only bug fix

### LINKED ISSUE #9278: Management script not edittable until saved
### What happened?

I ran into this issue modifying the management toolbox scripts.  This is also an issue if add a management script using the add model functionality as well.
I was unable to change anything in the script editor until it was compiled/saved.

### What Operating System are you on?

Windows

### PR DESCRIPTION
**Pull request by ric394**
resolves #9278

This was a read-only issue.

This checks for a vertical scrollbar in the managers editor (meaning the script is quite long) and makes it do buffer checks before making text writable.
If however a manager's editor does not have a vertical scrollbar it will skip buffer checks and make the text writable.

### CODE REVIEW

File: ApsimNG/Views/ManagerView.cs [hunk 1]
```diff
@@ -66,29 +62,42 @@ public void OnPageChanged(object sender, EventArgs e)
...
-                scriptEditor.ReadOnly = false;
+                cursor = scriptEditor.Location;
                 notebook.Drawn -= OnDrawn;
-                if (cursor != null && this.TabIndex == TAB_SCRIPT)
+                return;
+            }
+
+            if (this.TabIndex == TAB_SCRIPT)
+            {
+                if (cursor.ScrollH.Upper == scriptEditor.Location.ScrollH.Upper)
```
Comment (ric394) [inline ApsimNG/Views/ManagerView.cs:91]: This seems like the wrong orientation to me. Should it be ScrollV?

Comment (par456) [reply ApsimNG/Views/ManagerView.cs:91]: right yeah...it should be

Comment (ric394) [reply ApsimNG/Views/ManagerView.cs]: That works really well!
