### PR TITLE
Restructure the apex model

### LINKED ISSUE #3077: Apex model is not working as expected
In the Apex model, the group size and age are not working as expected especially when calculating the live stem number (the one we observed in the field)

### PR DESCRIPTION
**Pull request by byzheng**
resolves #3077

### CODE REVIEW

File: Models/Plant/Structure/Structure.cs [hunk 1]
```diff
@@ -80,6 +81,10 @@ public class Structure : Model
         [Link]
         public IFunction branchMortality = null;
 
+        /// <summary>The leaf apex model</summary>
+        [Link(IsOptional = true)]
+        public IApex Apex = null;
+
```
Comment (hol353) [inline Models/Plant/Structure/Structure.cs]: The only reason you're including apex into structure is so that you can call DoCalculations. This doesn't seem right. Instead, can ApexBase subscribe to event 

[EventSubscribe("DoPotentialPlantGrowth")]
private void OnDoPotentialPlantGrowth(object sender, EventArgs e)

Also we don't want any optional functions.

File: Models/Plant/Structure/ApexBase.cs [hunk 2]
```diff
@@ -28,8 +79,8 @@ public abstract class ApexBase : Model, IApex
         [ChildLink]
         private IFunction stemSenescenceAge = null;
 
-        /// <summary>The number of apex in each age group.</summary>
-        private List<double> apexGroupSize = new List<double>();
+        /// <summary>The apex group.</summary>
+        public List<double> apexGroupSize = new List<double>();
```
Comment (hol353) [inline Models/Plant/Structure/ApexBase.cs]: public fields aren't allowed. Turn into a public property starting with an uppercase letter.

**Comment by byzheng** [comment]
The state variables apexGroupSize and apexGroupAge is updated every day in the structure or others, but not in the LeafCohort. In the LeafCohort, apexGroupSize and apexGroupAge is kept when leaf appearance (no update after appearance).

Not sure how to structure these codes. 

DoPotentialPlantGrowth can be used to call DoCalculation, but still need to find a place to store the Apex interface.

**Comment by hol430** [comment]
retest this please jenkins

File: Models/Plant/Structure/Structure.cs (hunk 1 above)
Comment (hol353) [reply Models/Plant/Structure/Structure.cs]: Bangyou, can you now remove this link in structure.cs. I don't think it is needed. The apex model will still be loaded into memory and will run without this link. If you keep the IsOptional link in LeafCohort then it should be able to find the apex model even though it is a child of the Structure class. Try it and see if it works.

Comment (byzheng) [reply Models/Plant/Structure/Structure.cs]: @hol353 I have removed the link in Structure and keep IsOptional in the LeafCohort as you suggested.
