### PR TITLE
9727 Apsim Importer can handling missing soultes/initialwater

### LINKED ISSUE #9727: System.NullReferenceException when converting Classic soils
### What happened?

[Test.zip](https://github.com/user-attachments/files/19062108/Test.zip)

The `Chemical` model expects some Double values, which may not be present. Should the convertor add depths to Solutes, add zeros for N values, or the error be more informative? 

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at UserInterface.Presenters.ProfilePresenter.PopulateChemicalGraph(GraphView graph, Double[] thickness, Double[] pH, PHUnitsEnum phUnits, IEnumerable`1 solutes) in ApsimNG\Presenters\ProfilePresenter.cs:line 277
   at UserInterface.Presenters.ProfilePresenter.Refresh() in ApsimNG\Presenters\ProfilePresenter.cs:line 166
```

Image

### What Operating System are you on?

Windows

### PR DESCRIPTION
**Pull request by par456**
Resolves #9727 

Refactored the importer solutes code to handle if solutes is missing and give the new solutes the default values and layer structure from Water.

Also added default value of 100% full for initialwater if that node is missing from the apsim file. All defaults are based on what Apsim 7.10 uses as defaults for components when added new.

### CODE REVIEW

File: Tests/UnitTests/ImporterTests.cs [hunk 1]
```diff
@@ -421,5 +421,24 @@ public void EnsureMemoImports()
             Assert.That(memo, Is.Not.Null);
             Assert.That(memo.Text, Is.EqualTo("hello there"), "Failed to import memo message from .apsim file");
         }
+
+        [Test]
+        public void TestInitialEmptySolutesInitialisesSolutes()
```
Comment (ric394) [inline Tests/UnitTests/ImporterTests.cs:426]: The only thing I would suggest is to change the name of this to what it actually tests. Something like 'TestImporterInitialisesSolutesAndWaterBalances'

**Review by ric394 — APPROVED** [review]
