### PR TITLE
8031 Expression Exception Leak

### LINKED ISSUE #8031: "Failed to publish even SubscribeToEvents" error when running >360 simulations
### What happened?

This error started to occur after I updated my computer so there is a chance that this is an error/issue particular to my computer.

These are links to a simplified version of the APSIMX file (but still complex enough to generate the error below) and the corresponding met files:

https://csiroau-my.sharepoint.com/:u:/r/personal/pas075_csiro_au/Documents/Documents/Simulation%20Paper%20TOS/Simulation%20that%20crashes/SimplifiedSim.apsimx?csf=1&web=1&e=kbu4dx
https://csiroau-my.sharepoint.com/:f:/r/personal/pas075_csiro_au/Documents/Documents/Simulation%20Paper%20TOS/Simulation%20that%20crashes/Weather%20Files?csf=1&web=1&e=7pEY4R

When I run 2 sites (~360 sims), it runs without error, but when I add a 3rd, I get the following error:

ERROR in file: C:\Users\Pas075\OneDrive - CSIRO\Documents\Simulation Paper TOS\SDxLocAnalysis.apsimx
Simulation name: SimSow53SitePampasIW0.78
Models.Core.SimulationException
 ---> System.Exception: Failed to publish event SubscribeToEvents. Error from subscriber SubscribeToEvents.OnConnectToEvents
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.Compilation.ValidateReferences[T](IEnumerable`1 references)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.Create(String assemblyName, CSharpCompilationOptions options, IEnumerable`1 syntaxTrees, IEnumerable`1 references, CSharpCompilation previousSubmission, Type returnType, Type hostObjectType, Boolean isSubmission)
   at Models.Core.ScriptCompiler.CompileTextToAssembly(String code, IEnumerable`1 referencedAssemblies, String& sourceName) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\ScriptCompiler.cs:line 229
   at Models.Core.ScriptCompiler.Compile(String code, IModel model, IEnumerable`1 referencedAssemblies) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\ScriptCompiler.cs:line 81
   at Models.Functions.CSharpExpressionFunction.Compile[T](String expression, IModel relativeTo, ScriptCompiler compiler, T& function, String& errorMessages) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Functions\CSharpExpressionFunction.cs:line 72
   at Models.ExpressionReportFrequency.TryParse(String line, Report report, IEvent events, ScriptCompiler compiler) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Report\ExpressionReportFrequency.cs:line 32
   at Models.Report.SubscribeToEvents() in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Report\Report.cs:line 125
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Models.Core.Events.Publish(String eventName, Object[] args) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Events.cs:line 147
   --- End of inner exception stack trace ---
   at Models.Core.Events.Publish(String eventName, Object[] args) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Events.cs:line 151
   at Models.Core.Simulation.Prepare() in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 261
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Prepare() in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Simulation.cs:line 265
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 213

### What Operating System are you on?

Windows

### PR DESCRIPTION
**Pull request by par456**
Resolves #8031

Change how it tries to parse frequencies, so that it can both handle things with names and expressions with symbols. Added unit tests for both as well to pick this up in the future.

### CODE REVIEW

File: Models/Report/EventReportFrequency.cs [hunk 1]
```diff
@@ -23,31 +23,23 @@ public static bool TryParse(string line, Report report, IEvent events)
...
             }
-            else if (tokens.Length > 1)
+            else 
+                if (tokens.Length > 1 && line.Contains(' ') 
+                                      && !line.Contains('=')
+                                      && !line.Contains('<')
+                                      && !line.Contains('>')
+                                      && !line.Contains('&')
+                                      && !line.Contains('|'))
             {
```
Comment (hol353) [inline Models/Report/EventReportFrequency.cs:35]: I wonder if it would be cleaner to use ```line.IndexOfAny(new char[] { '=', '<', '>', '&','|') == 0```

Comment (par456) [reply Models/Report/EventReportFrequency.cs:30]: I went looking for something like that when I was first writing it but didn't find any good suggestions. Have made that change and tested it works.
