### PR TITLE
weather filename path bug fixed with tests

### LINKED ISSUE #8571: The examples don't run out of the box on Linux or MacOS
### What happened?

On Linux and MacOS, the back slashes in the weather path ("%root%\\Examples\\WeatherFiles\\Dalby.met") need to be converted to forward slashes.

### What Operating System are you on?

Linux

### PR DESCRIPTION
**Pull request by ric394**
resolves #8571

### CODE REVIEW

File: Tests/UnitTests/Weather/WeatherTests.cs [hunk 1]
```diff
@@ -186,6 +187,30 @@ public void TestGetAnyDayMetData()
             Assert.AreEqual(weather1900.Rain, weather.TomorrowsMetData.Rain, 0.01);
         }
 
+        /// <summary>
+        /// Ensures all example .met files contain %root%
+        /// </summary>
+        [Test]
+        public void TestAllExampleFilesWeatherModelsHaveRootReferenceInFileName()
```
Comment (hol353) [inline Tests/UnitTests/Weather/WeatherTests.cs:194]: Does this also check that the slashes are forward slashes? I think we need that.
