### PR TITLE
8819 Root Growth Changes

### LINKED ISSUE #8819: Root Growth Using wrong layer
### What happened?

When root growth is checking the layer for water, it seems to be looking at the layer above where it currently is. Aka, if there is no water below 600mm, it's still growing to the bottom of the next layer before it stops.

Investigating further.

### What Operating System are you on?

Windows

### PR DESCRIPTION
**Pull request by par456**
Resolves #8819

### CODE REVIEW

File: Models/Functions/SoilWaterScale.cs [hunk 1]
```diff
@@ -10,33 +11,77 @@ namespace Models.Functions
...
+    [Description("A simple scale to convert soil water content into a value between 0 and 2 where 0 = LL/LL15, 1 = DUL and 2 = SAT")]
     public class SoilWaterScale : Model, IFunction
     {
-        [Link]
-        IPhysical physical = null;
+
+        /// <summary> </summary>
+        [Description("SAT array internal variable: ")]
+        [Display(Type = DisplayType.None)]
+        public string SATModel { get; set; } = "[Physical].SAT";
```
Comment (hol353) [inline Models/Functions/SoilWaterScale.cs:23]: Why do we need to let the user specify a SATModel? I can't think of a use case.

File: Models/Functions/SoilWaterScale.cs [hunk 2]
```diff
@@ -10,33 +11,77 @@ namespace Models.Functions
...
+
+        /// <summary> </summary>
+        [Description("DUL array internal variable: ")]
+        [Display(Type = DisplayType.None)]
+        public string DULModel { get; set; } = "[Physical].DUL";
```
Comment (hol353) [inline Models/Functions/SoilWaterScale.cs:28]: As above, why do we need this?

File: Models/Functions/SoilWaterScale.cs [hunk 3]
```diff
@@ -10,33 +11,77 @@ namespace Models.Functions
...
 
-            double sws;
+            if (arrayIndex >= soilwater.SW.Length)
+                throw new Exception($"Soil Water Scale ({Parent.Name}.{Name}): ArrayIndex {arrayIndex} is more than SoilWater SW length {soilwater.SW.Length}.");
+
+            if (sats == null && duls == null && lls == null) 
+            {
+                sats = Locator.Get(SATModel) as double[];
+                duls = Locator.Get(DULModel) as double[];
+                lls = Locator.Get(LLModel) as double[];
```
Comment (hol353) [inline Models/Functions/SoilWaterScale.cs:58]: Locator.Get is slow at runtime. Move the call to StartOfSimulation. No need to do it everyday of the sim.

File: Models/Functions/SoilWaterScale.cs [hunk 4]
```diff
@@ -10,33 +11,77 @@ namespace Models.Functions
...
+
+        /// <summary> </summary>
+        [Description("DUL array internal variable: ")]
+        [Display(Type = DisplayType.None)]
+        public string DULModel { get; set; } = "[Physical].DUL";
+
+        /// <summary> </summary>
+        [Description("Lower Limit array internal variable: ")]
+        [Display(Type = DisplayType.None)]
+        public string LLModel { get; set; } = "[Physical].LL15";
```
Comment (hol353) [inline Models/Functions/SoilWaterScale.cs:33]: This one makes sense. The use case is the user wants to specify one of airdry, ll15, crop ll. Rather than a string I wonder about using an enum instead. That way the user gets a drop down rather than free form text.

File: Models/PMF/Organs/Root.cs [hunk 5]
```diff
@@ -180,8 +183,6 @@ public class Root : Model, IWaterNitrogenUptake, IArbitration, IOrgan, IOrganDam
         /// <summary>The N supply for reallocation</summary>
         private double nReallocationSupply = 0.0;
 
-        private SoilCrop soilCrop;
```
Comment (hol353) [inline Models/PMF/Organs/Root.cs:183]: Why has soilCrop been made a public property of Root?

**Review by hol353 — CHANGES_REQUESTED** [review]

File: Models/PMF/Organs/Root.cs (hunk 5 above)
Comment (par456) [reply Models/PMF/Organs/Root.cs:183]: That was to avoid copying the name matching code over to SoilWaterScale, as Root already has a reference to the SoilCrop.

If there is another place a reference to SoilCrop is available, I'm happy to use that, I just don't want to do the same string name matching again in SoilWaterScale.

File: Models/Functions/SoilWaterScale.cs (hunk 4 above)
Comment (par456) [reply Models/Functions/SoilWaterScale.cs:33]: I like that idea better, it'll make it easier to use, will change to enum.

File: Models/PMF/Organs/Root.cs (hunk 5 above)
Comment (hol353) [reply Models/PMF/Organs/Root.cs:183]: Ok that makes sense. Leave it as it is.

**Comment by par456** [comment]
Should be right to merge now.

**Review by hol353 — APPROVED** [review]
