### PR TITLE
Fix duplicate sibling name issue + handling for empty datetime cell in excel sheet when graphing

### LINKED ISSUE #8713: Not a legal OleAut date
### What happened?

A new bug in the graphing that I ran into: 

A date value of -693593 was tried to converted to a date in the LineSeriesWithTracker class and crashed. Click on the left-most point of the phenology graph in the Mouse experiment in Wheat validation -> South Australia.

image

### What Operating System are you on?

Windows

### PR DESCRIPTION
**Pull request by ric394**
resolves #8713

### CODE REVIEW

**Comment by par456** [comment]
Conflicts to solve on this branch

File: ApsimNG/Views/GraphView.cs [hunk 1]
```diff
@@ -2015,6 +2016,44 @@ private void OnChartMouseMove(object sender, OxyMouseEventArgs e)
             {
                 e.Handled = false;
                 inRightClick = false;
+
```
Comment (par456) [inline ApsimNG/Views/GraphView.cs:2019]: This was removed in the water presenter branch, pull it out of this one so it doesnt get merged back in.

Comment (ric394) [reply ApsimNG/Views/GraphView.cs:2019]: Now removed on branch.
