### PR TITLE
A few more fixes to BiomassRemovalEvent

### LINKED ISSUE #9956: Biomass removals not working
### What happened?

The test and example for biomass removals are not working because some of the code has been refactored but the json files using it were not converted.  

The tests are also a bit complex and some cleaner tests are needed

### What Operating System are you on?

Windows

### PR DESCRIPTION
**Pull request by HamishBrownPFR**
Resolves #9956

### CODE REVIEW

**Comment by HamishBrownPFR** [comment]
@par456 @hol353 @ric394 this is ready for review.

File: Models/Management/BiomassRemovalEvents.cs [hunk 1]
```diff
@@ -136,13 +136,11 @@ public void Remove()
                 }
             }
 
-            double stage;
-            double.TryParse(StageToSet, out stage);
-            if (!double.IsNaN(stage) && stage >= 1.0)
+            if ((StageToSet != "")&&(StageToSet != null))
```
Comment (ric394) [inline Models/Management/BiomassRemovalEvents.cs:139]: Consider using `!string.IsNullOrEmpty(StageToSet)`

Comment (HamishBrownPFR) [reply Models/Management/BiomassRemovalEvents.cs]: Nice tip thanks.  Change made an pushed up.  Please check again and merge if OK

**Review by ric394 — APPROVED** [review]
