### PR TITLE
Fix several reporting defects

### LINKED ISSUE #4520: Problems with report
In the attached simulation there are multiple problems with the report model.

1. In 'report1', the two WaterUptake variables don't produce the correct results. There should be a value of uptake for each layer for two zones e.g. columns should be:
[Eucalyptus].FineRoot.Zones[1].WaterUptake[1]
[Eucalyptus].FineRoot.Zones[1].WaterUptake[2]
...
[Eucalyptus].FineRoot.Zones[2].WaterUptake[1]
[Eucalyptus].FineRoot.Zones[2].WaterUptake[2]
...

2. In 'report2', the columns output should be same as above.
3. In 'report3', an exception should occur. Array indexing in report should be 1 but when I access index 0 it produces output instead of throwing an exception.
4. In 'reporttop', the commented variable throws an exception when it shouldn't.
5. The 'CumulativeGraph' is blank. I have ticked 'Cumulative' beside the Y variables in both series. When I do that the graph disappears
[Test.zip](https://github.com/APSIMInitiative/ApsimX/files/3948524/Test.zip)
.

### PR DESCRIPTION
**Pull request by hol353**
Resolves #4520

### CODE REVIEW

**Comment by hol430** [comment]
retest this please jenkins

File: Tests/UnitTests/Report/ReportDataTests.cs [hunk 1]
```diff
@@ -62,29 +62,6 @@ public void WholeArraysToTable()
             "     5,     6,                  8.000,                  9.000,     7\r\n");
         }
 
-        /// <summary>Convert partial arrays to a table with correct headings.</summary>
-        [Test]
```
Comment (hol430) [inline Tests/UnitTests/Report/ReportDataTests.cs]: Why delete this tests?

Comment (hol353) [reply Tests/UnitTests/Report/ReportDataTests.cs]: I didn't. I renamed the test and added extra ones.
