### PR TITLE
Fix unneeded redrawing of grid.

### LINKED ISSUE #9099: BiomassRemovalEvents model throws a null object reference
### What happened?

When ever clicking on a BiomassRemovalEvents model in the tree it throws a null object instance in GridPresenter.cs

### What Operating System are you on?

Windows

### PR DESCRIPTION
**Pull request by hol353**
Resolves #9099

### CODE REVIEW

File: ApsimNG/Presenters/GridPresenter.cs [hunk 1]
```diff
@@ -224,7 +224,7 @@ public void PopulateWithDataProvider(ISheetDataProvider dataProvider)
         }
 
         /// <summary>Refresh the grid.</summary>
-        public void Refresh()
+        public void     Refresh()
```
Comment (ric394) [inline ApsimNG/Presenters/GridPresenter.cs:227]: There seems to unnecessary extra whitespace here 🤔

File: ApsimNG/Presenters/GridPresenter.cs [hunk 2]
```diff
@@ -496,7 +496,7 @@ private void OnModelChanged(object changedModel)
                 model = (changedModel as GridTable).Model;
             else model = changedModel as IModel;
             dataProvider = ModelToSheetDataProvider.ToSheetDataProvider(model);
-            SetupSheet(dataProvider);
+            //SetupSheet(dataProvider);
```
Comment (ric394) [inline ApsimNG/Presenters/GridPresenter.cs:499]: remove commented code

**Comment by hol353** [comment]
@ric394 Should be ok now.

**Review by ric394 — APPROVED** [review]
