### PR TITLE
8373 Fix so SurfaceOrganicMatter.Add can take no3 and nh4

### LINKED ISSUE #8373: Specify N form in organic matter addition
### What is your question?

Hi, I am trying to add slurry applications to my simulations using the operation model. However, looking at the Models/Interfaces/ISurfaceOrganicMatter.cs file I do not see the type of N among the list. I was thinking to combine it with multiple mineral fertilizer applications to simulate NH4 and NO3 addition but I do not see how to specify the amount of organic N.
Thank you

### PR DESCRIPTION
**Pull request by par456**
Resolves #8373

Changes that were explained in the issue. Please check that this was implemented correctly before merging.

### CODE REVIEW

File: Models/Interfaces/ISurfaceOrganicMatter.cs [hunk 1]
```diff
@@ -13,7 +13,9 @@ public interface ISurfaceOrganicMatter
         /// <param name="type">Type of the biomass.</param>
         /// <param name="name">Name of the biomass written to summary file</param>
         /// <param name="fractionStanding">Fraction standing. Defaults to 0</param>
-        void Add(double mass, double N, double P, string type, string name, double fractionStanding = 0);
+        /// <param name="no3">The amount of no3 added (kg/ha).</param>
+        /// <param name="nh4">The amount of nh4 added (kg/ha).</param>
+        void Add(double mass, double N, double P, string type, string name, double fractionStanding = 0, double no3 = 0, double nh4 = 0);
     }
```
Comment (hol353) [inline Models/Interfaces/ISurfaceOrganicMatter.cs:19]: Change the defaults for no3 and nh4 to -1 to match SurfaceOrganicMatter.

Comment (par456) [reply Models/Interfaces/ISurfaceOrganicMatter.cs:19]: Fixed
