### PR TITLE
Fix CN reduction for tillage

### LINKED ISSUE #9724: CN reduction for tillage is applied twice
### What happened?

1. On line 95 using `CNReductionForTillage`. However, `TillageCompleted` is not implemented so I am not sure if those variables are ever set. Also in `CNReductionForTillage`, CN reduction is calculated based on `weather.Rain`, not `soil.PotentialRunoff`. 

2. On lines 103-105 (using soil.PotentialRunoff, which accounts for canopy interception). 

Image

### What Operating System are you on?

Windows

### PR DESCRIPTION
**Pull request by BrianCollinss**
Resolves #9724

Ready to merge. I removed the code from `RunoffModel` and tried to complete `CNReductionForTillage` in a way that does not need an extra event (`TillageCompleted`) to be published. If the event is implemented, these parameters can be removed from `RunoffModel` and moved to `CNReductionForTillage`. 

```
        /// <summary>Cumulative rainfall below which tillage reduces CN (mm).</summary>
        public double TillageCnCumWater { get; set; }
        /// <summary>Reduction in CN due to tillage()</summary>
        public double TillageCnRed { get; set; }
        /// <summary>Running total of cumulative rainfall since last tillage event. Used for tillage CN reduction (mm).</summary>
        public double CumWaterSinceTillage { get; set; }
```

In one example I used, this did not change results. The reason could be that `CNReductionForTillage` was never doing anything and all the reduction was done inside the `RunoffModel`. Now, at least the order and logic of things are correct.

### CODE REVIEW

**Comment by BrianCollinss** [comment]
This is ready to merge if approved @par456

File: Models/Soils/WaterModel/CNReductionForTillage.cs [hunk 1]
```diff
@@ -37,38 +37,46 @@ public class CNReductionForTillage : Model, IFunction
...
+            {
+                runoffModel = parent as RunoffModel;
+
+                cumWaterSinceTillage = runoffModel.CumWaterSinceTillage;
+                tillageCnCumWater = runoffModel.TillageCnCumWater;
+                tillageCnRed = runoffModel.TillageCnRed;
+            }
+            else
+            {
+                throw new Exception("Parent model of CNReductionForTillage must be RunoffModel.");
```
Comment (ric394) [inline Models/Soils/WaterModel/CNReductionForTillage.cs:59]: Instead of using this if statement, change line 18 from `WaterBalance` to `RunoffModel`.

**Review by ric394 — COMMENTED** [review]
I'm happy with this code-wise. Is someone available to review from a scientific standpoint?

**Comment by BrianCollinss** [comment]
@ric394 Thanks for the review. All I did was to clean up the runoff class so it does not do the same calculation twice. The only reason it did not use to run it twice (mistakenly) was that `TillageCompleted` event is not implemented.

**Comment by hol353** [comment]
This looks fine to me. Go ahead and merge @ric394
