### PR TITLE
8476 Fixing Manager View Bugs

### LINKED ISSUE #8476: Manager editing buglets
### What happened?

\<ctrl>-T doesnt test the script compilation (for errors) any more

\<ctrl>-S (save) changes insertion to [0,0] and moves view to origin

Clicking on / off the component resets the view to origin (editing position isnt preserved)

Weird stuff happens when errors are present and the component is copied/duplicated (may be related to https://github.com/APSIMInitiative/ApsimX/pull/8458)

### What Operating System are you on?

Linux

### PR DESCRIPTION
**Pull request by par456**
Resolves #8476 

List of errors fixed:
- No more Invisible Manager copies when a non-compiling manager was copied.
- Disabled Managers will not try and compile
- Property page holds position when editing values
- Script cannot be edited while the text buffer is still loading the script
- Run button now runs whatever is in the script, even if it hasn't been saved or clicked off
- Parameters bug was fixed by #8890
- Pressing ctrl-s to save will now report script errors after the save is completed
- Clicking "more info" with the offending script open will display the correct error message.

### CODE REVIEW

File: ApsimNG/Interfaces/IManagerView.cs [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+
+namespace UserInterface.Views
+{
+    public interface IManagerView
+    {
+        /// <summary>
+        /// Provides access to the properties grid.
+        /// </summary>
+        /// <remarks>
+        /// Change type to IProeprtyView when ready to release new property view.
```
Comment (ric394) [inline ApsimNG/Interfaces/IManagerView.cs:12]: A bit of a nit pick but there is a spelling mistake

**Review by ric394 — COMMENTED** [review]
See comment.
