### PR TITLE
worldmodel url wants "." instead of ","

### LINKED ISSUE #6917: Weather downloader is not culture-sensitive
The weather downloader can fail under certain system-wide date/number formatting settings (e.g. if the default number format uses a comma for the decimal separator).

### PR DESCRIPTION
**Pull request by dexy58**
Fixes url when using NASA POWER w/ CHIRPS rainfall (World Modellers) radio button

When inserting latitude and longitude you have to use "," as decimal placement instead of "." (an error will pop up). However worldmodel webiste needs to have "." instead of "," in it's url.

Resolves #6917

### CODE REVIEW

File: ApsimNG/Utility/WeatherDownloadDialog.cs [hunk 1]
```diff
@@ -653,6 +653,10 @@ public string GetNasaChirps()
                 ShowMessage(MessageType.Warning, "NASA/CHRIPS data end date can be no later than yesterday", "Invalid end date");
                 return null;
             }
+
+            entryLatitude.Text = entryLatitude.Text.Replace(',', '.');
```
Comment (hol430) [inline ApsimNG/Utility/WeatherDownloadDialog.cs:657]: Instead of doing a straight text replace here, I think it will be better to 

1. Convert the lat/long input strings to doubles (using the current culture) - this will account for things like ',' as decimal separator or '.' as thousands separator as may be the case on the user's system
2. Convert these parsed doubles back to strings (using the invariant culture) - this will generate a string in the american format (ie using '.' for decimal separator), which should be safe to pass into the API

ie something like this:

```csharp
double latitude = double.Parse(entryLatitude.Text, CultureInfo.CurrentCulture);
double longitude = double.Parse(entryLongitude.Text, CultureInfo.CurrentCulture);

string latitudeStr = latitude.ToString(CultureInfo.InvariantCulture);
string longitudeStr = longitude.ToString(CultureInfo.InvariantCulture);
// (and then use latitudeStr/longitudeStr as parameters to the climate API)
```

**Review by hol430 — CHANGES_REQUESTED** [review]

File: ApsimNG/Utility/WeatherDownloadDialog.cs (hunk 1 above)
Comment (dexy58) [reply ApsimNG/Utility/WeatherDownloadDialog.cs:657]: Hello :)

Do I have to commit this to the patch-1 branch on dexy58/ApsimX to make the change? I have never done this (this is the 1st time I am contributing to the open source project, so I don't know the procedure).
Thanks.

Comment (dexy58) [reply ApsimNG/Utility/WeatherDownloadDialog.cs]: Okay, I commited the changes in patch-1 branch on dexy58/ApsimX and it seems it has done the trick. It works, but I had to change a few other things because of those changes. Check them if you think we should revert it.

**Comment by hol430** [comment]
retest this please jenkins

**Review by hol430 — APPROVED** [review]
Looks good - thanks for the contribution @dexy58!
