### PR TITLE
Female.NumberOfBirthsThisTimeStep fixes

### LINKED ISSUE #9045: CLEM summary reporting of births
### What happened?

The number of births in a time-step for reporting is not working as it doesn't get reset after births.

### What Operating System are you on?

Windows

### PR DESCRIPTION
**Pull request by lie112**
Resolves #9045 
Also addresses aspects of #8997

### CODE REVIEW

**Comment by par456** [comment]
Is this ready to be merged in?

**Comment by lie112** [comment]
Yes. When I use resolves it is right to go.
I just included the other issue id for future tracking.

File: Models/CLEM/Activities/RuminantActivityBreed.cs [hunk 1]
```diff
@@ -312,6 +312,10 @@ private void OnCLEMAnimalBreeding(object sender, EventArgs e)
             // get list of all pregnant females
             List<RuminantFemale> pregnantherd = CurrentHerd(true).OfType<RuminantFemale>().Where(a => a.IsPregnant).ToList();
 
+            // Need to reset births this time step for all non pregnant.
+            // Find a place where individuals are identified on stime step after births to reset this value.
+            _ = CurrentHerd(true).OfType<RuminantFemale>().Where(a => !a.IsPregnant).Select(a => a.NumberOfBirthsThisTimestep == 0);
```
Comment (hol353) [inline Models/CLEM/Activities/RuminantActivityBreed.cs:317]: Does this actually do anything? It stores the result of the .Select into a unnamed variable (i.e. _)

Comment (lie112) [reply Models/CLEM/Activities/RuminantActivityBreed.cs:317]: Yes, it resets the NumberOfBirthsThisTimestep for each non-pregnant female, but doesn't have a return value we need to keep. It's just done in a LINQ statement rather than use a loop over the filtered group of individuals.

Comment (hol353) [reply Models/CLEM/Activities/RuminantActivityBreed.cs:317]: Hmm. You're saying ```a.NumberOfBirthsThisTimestep == 0```, a conditional statement, resets the variable ```NumberOfBirthsThisTimestep```. The reader wouldn't expect this behaviour. It is not at all obvious. I suggest a method called something like ResetNumberOfBirthsThisTimestep() that makes it obvious.

Comment (lie112) [reply Models/CLEM/Activities/RuminantActivityBreed.cs:317]: Your right! This is wrong (==) and has actually been depreciated with a correct calculation of BirthsThisTimeStep by counting the number of 0 day old sucklings. I'll commit the changes.
