### PR TITLE
Graph Legend Issue Fix

### LINKED ISSUE #8705: Graph Series cannot hide with legend
### What happened?

If you have two series that produce the same Legend items, clicking on the legend to hide a line doesn't work. You can get some functinoality back by disabling "show legend" on one of the series, which lets you turn off the other series with the legend, but still not that one.

For an example, look at graphs in the Wheat validation, I was working specifically with Lincoln2014 Canopy Cover.

### What Operating System are you on?

Windows

### PR DESCRIPTION
**Pull request by ric394**
resolves #8705

- This allows the turning on/off of legend items to control both series in under a graph if they have the same 'series'.
- Also added a small change to ApsimNG.csproj file to allow breakpoint functionality for vs code.

### CODE REVIEW

File: ApsimNG/Views/GraphView.cs [hunk 1]
```diff
@@ -1173,7 +1212,10 @@ private void EnsureMonotonic(double[] x)
         /// </summary>
         /// <param name="legendPositionType">Position of the legend</param>
         /// <param name="orientation">Orientation of items in the legend.</param>
-        public void FormatLegend(APSIM.Shared.Graphing.LegendPosition legendPositionType, APSIM.Shared.Graphing.LegendOrientation orientation)
+        /// <param name="namesOfSeriesToRemove">Names of Series to remove.</param>
+        /// <param name="reselectedSeriesNames">Names of series to reenable.</param>
+        [Obsolete]
```
Comment (par456) [inline ApsimNG/Views/GraphView.cs:1217]: Remove Obsolete so we don't need to silence warnings

File: ApsimNG/Views/GraphView.cs [hunk 2]
```diff
@@ -178,6 +179,43 @@ protected override void Initialise(ViewBase ownerView, GLib.Object gtkControl)
...
+                        else if ((series as OxyPlot.Series.Series).IsVisible == true && (series as OxyPlot.Series.Series).Title != null && seriesNamePreviouslyUnselected)
+                            reselectedSeriesNames.Add(series.Name);
+                    }
+                    UnselectedSeriesNames = newUnselectedSeriesNames;
+                    LegendPosition legendPosition;
+                    LegendOrientation legendOrientation;
+                    Enum.TryParse((sender as PlotModel).Legends.First().LegendPosition.ToString(), out legendPosition);
+                    Enum.TryParse((sender as PlotModel).Legends.First().LegendOrientation.ToString(), out legendOrientation);
+                    // Reformat the legend without the matching unselectedSeries.
+    #pragma warning disable CS0612 // Type or member is obsolete
```
Comment (par456) [inline ApsimNG/Views/GraphView.cs:212]: Remove all the pragmas disables

File: ApsimNG/Presenters/WaterPresenter.cs
Comment (par456) [inline ApsimNG/Presenters/WaterPresenter.cs:1]: Remove all the pragmas disables

File: ApsimNG/Presenters/ProfilePresenter.cs
Comment (par456) [inline ApsimNG/Presenters/ProfilePresenter.cs:1]: Remove all the pragmas disables

File: ApsimNG/Views/GraphView.cs [hunk 3]
```diff
@@ -1458,15 +1503,15 @@ private void FormatAxisTickLabels(OxyPlot.Axes.Axis axis)
...
                 }
 
-                if (axis.PlotModel.Series[0] is BoxPlotSeries &&
-                    axis.Position == OxyPlot.Axes.AxisPosition.Bottom &&
-                    axis.PlotModel.Series?.Count > 0)
-                {
-                    // Need to put a bit of extra space on the x axis.
-                    axis.MinimumPadding = (axis.ActualMaximum - axis.ActualMinimum) * 0.005;
-                    axis.MaximumPadding = (axis.ActualMaximum - axis.ActualMinimum) * 0.005;
+                //if (axis.PlotModel.Series[0] is BoxPlotSeries &&
```
Comment (par456) [inline ApsimNG/Views/GraphView.cs:1506]: Commented code to remove

**Review by par456 — CHANGES_REQUESTED** [review]

File: ApsimNG/Presenters/LegendPresenter.cs [hunk 4]
```diff
@@ -101,7 +101,7 @@ private void PopulateView()
 
             List<string> seriesNames = this.GetSeriesNames();
             this.view.SetSeriesNames(seriesNames.ToArray());
-            if (graph.DisabledSeries != null)
+            if (graph.DisabledSeries.Count() > 0)
```
Comment (par456) [inline ApsimNG/Presenters/LegendPresenter.cs:104]: You'll want to check both of these. Check if null, then check if count > 0

File: ApsimNG/Views/GraphView.cs [hunk 5]
```diff
@@ -1173,7 +1210,9 @@ private void EnsureMonotonic(double[] x)
         /// </summary>
         /// <param name="legendPositionType">Position of the legend</param>
         /// <param name="orientation">Orientation of items in the legend.</param>
-        public void FormatLegend(APSIM.Shared.Graphing.LegendPosition legendPositionType, APSIM.Shared.Graphing.LegendOrientation orientation)
+        /// <param name="namesOfSeriesToRemove">Names of Series to remove.</param>
+        /// <param name="reselectedSeriesNames">Names of series to reenable.</param>
+        public void FormatLegend(LegendPosition legendPositionType, LegendOrientation orientation, List<string> namesOfSeriesToRemove, List<string> reselectedSeriesNames)
```
Comment (par456) [inline ApsimNG/Views/GraphView.cs:1215]: Make the last two parameters optional with = null, then you don't have to go through all those other files and add nulls.

File: ApsimNG/Presenters/ProfilePresenter.cs [hunk 6]
```diff
@@ -199,7 +199,7 @@ public static void PopulateOrganicGraph(GraphView graph, double[] thickness, dou
             graph.FormatAxis(AxisPosition.Top, "Fresh organic matter (kg/ha)", inverted: false, xTopMin, xTopMax, double.NaN, false, false);
             graph.FormatAxis(AxisPosition.Left, "Depth (mm)", inverted: true, 0, height, double.NaN, false, false);
             graph.FormatAxis(AxisPosition.Bottom, "Fraction ", inverted: false, 0, 1.01, 0.2, false, false);
-            graph.FormatLegend(LegendPosition.BottomRight, LegendOrientation.Vertical);
+            graph.FormatLegend(LegendPosition.BottomRight, LegendOrientation.Vertical, null, null);
```
Comment (par456) [inline ApsimNG/Presenters/ProfilePresenter.cs:202]: If you make the change to FormatLegend, you can come back and remove all these.

**Review by par456 — APPROVED** [review]
